name: TEST CI GITHUB

permissions:
    contents: read

on: [
    push
]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Run tests
              run: |
                echo "Running tests..."
                # Add your test commands here 
                ls -la